apiVersion: v1
kind: Service
metadata:
  name: frontend-rpubkey-service
  namespace: web-pubkey
  labels:
    app: frontend-rpubkey
spec:
  selector:
    app: frontend-rpubkey
  ports:
  - name: metrics
    port: 443
    targetPort: 80
    protocol: TCP
  type: ClusterIP